spring:
    application:
        name: component-registry-rest

    datasource:
        hikari:
            connectionTimeout: 20000
            maximumPoolSize: 5
#        url: jdbc:postgresql://localhost:5443/compreg
#        username: <....>
#        password: <....>
